In [88]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [89]:
path_to_identities = '../../../Dataset/identity_CelebA.txt'
path_to_images_folder = '../../../Dataset/img_celeba_cropped'
path_to_attributes = '../../../Dataset/list_attr_celeba.txt'

In [90]:
labels = pd.read_csv(path_to_identities, sep="\s", names=["path", "identity"])

attributes = pd.read_csv(path_to_attributes, sep="\s+")
attributes['path'] = list(attributes.index)

labels = pd.merge(labels, attributes, on="path")

labels['path'] = path_to_images_folder + labels['path']
display(labels)

/var/folders/mx/1v4nf8c52yv1vdfw99lyg6qh0000gn/T/ipykernel_45215/3066700682.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  labels = pd.read_csv(path_to_identities, sep="\s", names=["path", "identity"])


path  identity  \
0       ../../../Dataset/img_celeba_cropped000001.jpg      2880   
1       ../../../Dataset/img_celeba_cropped000002.jpg      2937   
2       ../../../Dataset/img_celeba_cropped000003.jpg      8692   
3       ../../../Dataset/img_celeba_cropped000004.jpg      5805   
4       ../../../Dataset/img_celeba_cropped000005.jpg      9295   
...                                               ...       ...   
202594  ../../../Dataset/img_celeba_cropped202595.jpg      9761   
202595  ../../../Dataset/img_celeba_cropped202596.jpg      7192   
202596  ../../../Dataset/img_celeba_cropped202597.jpg      9852   
202597  ../../../Dataset/img_celeba_cropped202598.jpg      5570   
202598  ../../../Dataset/img_celeba_cropped202599.jpg     10101   

        5_o_Clock_Shadow  Arched_Eyebrows  Attractive  Bags_Under_Eyes  Bald  \
0                     -1                1           1               -1    -1   
1                     -1               -1          -1                1    -1   
2                     -1               -1          -1               -1    -1   
3                     -1               -1           1               -1    -1   
4                     -1                1           1               -1    -1   
...                  ...              ...         ...              ...   ...   
202594                -1               -1           1               -1    -1   
202595                -1               -1          -1               -1    -1   
202596                -1               -1          -1               -1    -1   
202597                -1                1           1               -1    -1   
202598                -1                1           1               -1    -1   

        Bangs  Big_Lips  Big_Nose  ...  Sideburns  Smiling  Straight_Hair  \
0          -1        -1        -1  ...         -1        1              1   
1          -1        -1         1  ...         -1        1             -1   
2          -1         1        -1  ...         -1       -1             -1   
3          -1        -1        -1  ...         -1       -1              1   
4          -1         1        -1  ...         -1       -1             -1   
...       ...       ...       ...  ...        ...      ...            ...   
202594     -1         1        -1  ...         -1       -1             -1   
202595      1         1        -1  ...         -1        1              1   
202596     -1        -1        -1  ...         -1        1             -1   
202597     -1         1        -1  ...         -1        1             -1   
202598     -1        -1        -1  ...         -1       -1             -1   

        Wavy_Hair  Wearing_Earrings  Wearing_Hat  Wearing_Lipstick  \
0              -1                 1           -1                 1   
1              -1                -1           -1                -1   
2               1                -1           -1                -1   
3              -1                 1           -1                 1   
4              -1                -1           -1                 1   
...           ...               ...          ...               ...   
202594         -1                -1           -1                 1   
202595         -1                -1           -1                -1   
202596         -1                -1           -1                -1   
202597          1                 1           -1                 1   
202598          1                -1           -1                 1   

        Wearing_Necklace  Wearing_Necktie  Young  
0                     -1               -1      1  
1                     -1               -1      1  
2                     -1               -1      1  
3                      1               -1      1  
4                     -1               -1      1  
...                  ...              ...    ...  
202594                -1               -1      1  
202595                -1               -1      1  
202596                -1               -1      1  
202597 

In [91]:
images = labels['path'].values
label = labels['identity'].values

In [92]:
dataset = tf.data.Dataset.from_tensor_slices((images, label))

In [93]:
for i in dataset.take(2):
    print(i)

(<tf.Tensor: shape=(), dtype=string, numpy=b'../../../Dataset/img_celeba_cropped000001.jpg'>, <tf.Tensor: shape=(), dtype=int64, numpy=2880>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'../../../Dataset/img_celeba_cropped000002.jpg'>, <tf.Tensor: shape=(), dtype=int64, numpy=2937>)


In [94]:
def process_images(filename, label):
    image_string = tf.io.read_file(filename)
    image = tf.image.decode_jpeg(image_string)
    image = tf.image.convert_image_dtype(image, tf.float32)
    image = tf.reshape(image, (28,28))
    return image, label

In [95]:
dataset = dataset.map(process_images)

dataset = dataset.batch(10)
dataset = dataset.prefetch(1)